### PR TITLE
Change colorcolumn from red to almost black

### PR DESCRIPTION
**Pull request by Lucasosf**
Hi guys, nice work with your colorscheme.

I made a change on my own fork of this repo, maybe you guys will like it too.

I change the ColorColumn from red to almost black. See the images.

red

better

Thanks

### CODE REVIEW

**Comment by Lucasosf** [comment]
What you think @romainl  ?

**Comment by romainl** [comment]
I'm OK with that change.

Could you also do it for the 16color section so that I can merge it in one move?

**Comment by Lucasosf** [comment]
Nice, @romainl done.

Thanks

**Comment by romainl** [comment]
Thank you for this and happy vimming!

**Pull request merged**
