### PR TITLE
Update Airline and Lightline Themes

### PR DESCRIPTION
**Pull request by djmoch**
## Summary
I've taken the liberty of updating the Airline/Lightline theme to something which I think is more in keeping with the goal of Apprentice being a "dark, low-contrast color scheme." The theme will look familiar to users of the Lightline "Wombat" color scheme, but the colors are all selected from the Apprentice palette.

## Screen Shots
The below screen shots are using the Airline theme, but the Lightline theme will look similar.
screen shot 2016-06-17 at 1 29 49 pm
screen shot 2016-06-17 at 1 30 26 pm
screen shot 2016-06-17 at 1 30 38 pm
screen shot 2016-06-17 at 1 31 08 pm

The Airline theme as configured results in the tabline looking like this (with the Lightline theme again being configured accordingly). The active tab is blue.
screen shot 2016-06-17 at 1 31 47 pm

### CODE REVIEW

**Comment by romainl** [comment]
I don't think the color for active "tabs" and "NORMAL" status line should be blue. `#87875F` is Apprentice's most important color and should be the main color for the status line and the tab line. ust like with apprentice itself.

**Comment by djmoch** [comment]
Okay, thats easy enough to change. Something like this then?
screen shot 2016-06-17 at 5 31 26 pm

Any other comments?

**Comment by romainl** [comment]
Looks good to me.

**Comment by romainl** [comment]
Thank you for your contribution.

**Pull request merged**
