### PR TITLE
Import changes from master and update fancylines

### PR DESCRIPTION
**Pull request by pt307**
I've imported `README.md` and `colors/apprentice.{erb,vim}` into the fancylines-and-neovim branch from master, and updated the airline and lightline files with the light_blue fix from #57.

I wanted to ask if you'd be okay with me trying to get the airline/lightline themes merged upstream - that way I (and others) who want to use these themes with Vim could just track the Apprentice master branch like everyone else.

Also, I don't know if you're aware - I've only just noticed it myself - but with the merge of #49 the only Neovim-specific config (terminal coloring) in this branch was removed. I'm not sure how you feel about rectifying that, given that 11 months has passed and nobody has raised an issue for it :)

### CODE REVIEW

**Comment by romainl** [comment]
The thing is that I actively don't *want* to support airline/lightline and Neovim. I kept that "fancylines-and-neovim" branch around as a courtesy to previous users who might have a use for it (there is at least one, apparently) but I have no plan to ever maintain it myself as its content is geared toward software I don't use and thus untestable.

While I can certainly press the green button on this PR, the chances of the airline/lightline/neovim-specific stuff finding its way back into master are exactly 0.

Now, one way to go forward could be for someone to fork this repo, merge "fancylines-and-neovim" back into "master" and try to keep up with upstream.

Another option could be to extract the airline/lightline-specific stuff into its own repo, possibly with the Neovim-specific stuff, that could live a life of its own.

I would happily update the `README.md` to point to that new repo.

**Comment by pt307** [comment]
Just to clarify - by upstream I meant the upstream repositories of [airline](https://github.com/vim-airline/vim-airline-themes) and [lightline](https://github.com/itchyny/lightline.vim), not the Apprentice upstream. That way the themes could be more easily maintained by the people who are most likely to use them, and the `fancylines-and-neovim` branch would become redundant.

**Comment by romainl** [comment]
Sorry for the confusion…. Yes I am OK with that as long as:

- the different licences are compatible or can be made compatible,
- it is made crystal-clear that I shouldn't be involved in their maintenance.

**Comment by pt307** [comment]
Both vim-airline and lightline.vim are under the MIT License, so no problems there.

I have reworked both theme files to make them more readable/easier to maintain in future while keeping the same colors applied to the various parts, so the reworked themes are identical in appearance to the themes in this repository. However, I have added a few extra bits to the airline theme to apply the Apprentice palette to other parts of the statusline that weren't previously themed (warnings, errors, and accents).

Maintenance requests for these themes would almost certainly come by way of GitHub Issues on the respective airline/lightline repositories. I have listed myself as Author in both files as each file has essentially been rewritten, and credited you alongside it - if this is not to your liking then please let me know, I will not be submitting the themes to the upstream repositories until I hear back from you.

The theme files:
- [airline](https://gist.github.com/pt307/01e50dcab3278be0f8b75bc3cd80db86)
- [lightline](https://gist.github.com/pt307/8caf35cb94c596e71ca74df925258bf1)

**Comment by romainl** [comment]
@pt307 I'm OK with that but there is one thing missing from those files: an explicit link to https://github.com/romainl/Apprentice/

Once they are pushed in their respective repositories, could you ping me so that I can change the `README.md`?

**Comment by pt307** [comment]
No problem, I'll add that in now and will let you know once they're accepted. Thanks!

**Pull request merged**
